export const rows = [
  {
    id: 1,
    date: "08-5-2022",
    status: "Approved ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 2,
    date: "08-5-2022",
    status: "Pending",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 3,
    date: "08-5-2022",
    status: "Pending ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 4,
    date: "08-5-2022",
    status: "Pending ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 5,
    date: "08-5-2022",
    status: "Pending ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 6,
    date: "08-5-2022",
    status: "Pending ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 7,
    date: "08-5-2022",
    status: "Pending",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 8,
    date: "08-5-2022",
    status: "Pending ",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
  {
    id: 9,
    date: "08-5-2022",
    status: "Pending",
    from: "Managing Director",
    to: "Head of IT Department",
    title: "Request for payment of outstanding balance",
  },
];
